x = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(x))
print('Esse valor é do tipo numérico? ', x.isnumeric())
print('É uma palavra? ', x.isalpha())
print('Tem letras e números? ', x.isalnum())
print('Está em letras maiúsculas? ', x.isupper())
print('Está em letras minúsculas? ', x.islower())
print('Só tem espaços? ', x.isspace())
print('Está capitalizada? ', x.istitle())